# Homebrew formula for Flow GTD
# Generated by: make brew-formula
#
# To use this formula:
#   1. Create a tap repository: github.com/jasonhotsauce/homebrew-flow
#   2. Copy this file to: homebrew-flow/Formula/flow-gtd.rb
#   3. Users install with:
#      brew tap jasonhotsauce/flow
#      brew install flow-gtd

class FlowGtd < Formula
  include Language::Python::Virtualenv

  desc "Local-First, AI-Augmented GTD CLI for Senior Engineering Managers"
  homepage "https://github.com/jasonhotsauce/flow-gtd"
  url "https://github.com/jasonhotsauce/flow-gtd/archive/refs/tags/v0.1.2.tar.gz"
  sha256 "a412c916ec3b58da7739ef9a6c889735d09722f151f478c6ae0c2be2fc012ebf"
  license "MIT"

  depends_on "python@3.11"

  def install
    # Manual virtualenv creation instead of virtualenv_create() helper
    # Reason: Homebrew Python may not have pip module available (especially on Apple Silicon)
    # The ensurepip bootstrap ensures pip is available before installing dependencies
    system "python3.11", "-m", "venv", libexec
    system libexec/"bin/python", "-m", "ensurepip", "--upgrade"
    system libexec/"bin/pip", "install", "--upgrade", "pip"
    
    # Install the package (reads dependencies from pyproject.toml)
    system libexec/"bin/pip", "install", buildpath
    
    # Symlink the flow command to bin
    bin.install_symlink libexec/"bin/flow"
  end

  def caveats
    <<~EOS
      Flow GTD requires an LLM API key for AI features.
      
      Set up your environment:
        export FLOW_GEMINI_API_KEY="your-api-key"
      
      Or run the onboarding wizard:
        flow
      
      Data is stored locally in:
        ~/.flow/data/
    EOS
  end

  test do
    assert_match "flow-gtd 0.1.2", shell_output("#{bin}/flow --version")
  end
end